apiVersion: v1
kind: Service
metadata:
  name: machine-learning
  labels:
    app: machine-learning
spec:
  selector:
    app: machine-learning
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 8080
  type: LoadBalancer
