apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
spec:
  selector:
    matchLabels:
      app: persistence
  replicas: 1
  template:
    metadata:
      labels:
        app: persistence
    spec:
      volumes:
      - name: model-persistance
        persistentVolumeClaim:
          claimName: model-pvc
      containers:
        - name: persistence
          image: "ratinacnikola/persistence-msvc:v0.2"
          ports:
            - name: http
              containerPort: 5000