apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
spec:
  selector:
    matchLabels:
      app: persistence
  replicas: 2
  template:
    metadata:
      labels:
        app: persistence
    spec:
      containers:
        - name: persistence
          image: "ratinacnikola/persistence-msvc:v0.1"
          ports:
            - name: http
              containerPort: 5000