apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
spec:
  selector:
    matchLabels:
      app: persistence
  replicas: 1
  template:
    metadata:
      labels:
        app: persistence
    spec:
      volumes:
      - name: model-data
        persistentVolumeClaim:
          claimName: model-pvc
      containers:
        - name: persistence
          image: "ratinacnikola/persistence-msvc:v1.0"
          volumeMounts:
            - 
              mountPath: /app/data/
              name: model-data
          ports:
            - name: http
              containerPort: 5000