apiVersion: v1
kind: Service
metadata:
  name: persistence
  labels:
    app: persistence
spec:
  selector:
    app: persistence
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort